# Generated by Django 5.0.1 on 2024-02-03 08:11

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'action'), ('FN', 'fantasy'), ('AD', 'adventure'), ('DR', 'drama'), ('HS', 'historical')], max_length=2),
        ),
    ]
