# Generated by Django 5.0.1 on 2024-02-03 10:05

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'action'), ('FN', 'fantasy'), ('AD', 'adventure'), ('DR', 'drama'), ('HS', 'historical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/book'),
        ),
    ]
